### ISSUE TITLE
sessionCreator reject() results in timeout on the client

### ISSUE THREAD

**Issue by birkir** [mikemintz/react-rethinkdb#28]
Don't know if it's a bug in react-rethindb package or the rethinkdb-websocket-client package. I'm not using bluebird.

Here's an example:
```javascript
// server
const sessionCreator = params => {
  return new Promise((resolve, reject) => {
    return reject('not authorized');
  });
};
````

```javascript
// client
session.connect({ ... })
session._connPromise.then(conn => console.info('got conn %o', conn))
.catch(err => console.error('got error %o', err)); // should be catch'd here?
```

Here is the error message on the client, which seems to be thrown from the WebSocket package.
```bash
Unhandled rejection ReqlTimeoutError: Could not connect to localhost:3000, operation timed out.
    at ReqlTimeoutError.ReqlError [as constructor] (eval at <anonymous> (http://localhost:3000/bundle.js:3693:2), <anonymous>:7022:14)
    at new ReqlTimeoutError (eval at <anonymous> (http://localhost:3000/bundle.js:3693:2), <anonymous>:7155:52)
    at eval (eval at <anonymous> (http://localhost:3000/bundle.js:3693:2), <anonymous>:5665:37)
```

**Comment by mikemintz** [comment]
I think that's like an issue with rethinkdb-websocket-server. Can you confirm that "not authorized" indeed shows up in your server logs?

**Comment by mikemintz** [comment]
Yes, this was indeed missing from rethinkdb-websocket-server, thanks for reporting it @birkir. It's resolved in latest master by https://github.com/mikemintz/rethinkdb-websocket-server/commit/3664e34c3fb62287a1cc0fcaaa23ff3fff805bba

Right now I'm just sending the same error message to the browser no matter what was specified in Promise.reject, so it always says "rethinkdb-websocket-server session rejected". That's an improvement over timing out, but it might be nice to propagate the actual message to the browser so the developer can handle it. But that could cause a security issue for developers that have until now been assuming the rejection message was only visible on the server side, so I'm not sure what's more important at this point.

**Comment by birkir** [comment]
Awesome, will continue to experiment. The message did show up on the server. Great work.
