### ISSUE TITLE
Chat example not works for me

### ISSUE THREAD

**Issue by rafaelgilead** [mikemintz/react-rethinkdb#43]
npm start

> example-chat@0.0.0 start /home/chat
> babel-node server/index.js

/home/chat/server/index.js:1
(function (exports, require, module, __filename, __dirname) { import { AuthManager } from './AuthManager';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at loader (/home/chat/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/chat/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Function.Module.runMain (module.js:604:10)
    at /home/chat/node_modules/babel-cli/lib/_babel-node.js:155:24
    at Object.<anonymous> (/home/chat/node_modules/babel-cli/lib/_babel-node.js:156:7)

npm ERR! Linux 3.14.32-xxxx-grs-ipv6-64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! example-chat@0.0.0 start: `babel-node server/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the example-chat@0.0.0 start script 'babel-node server/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the example-chat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node server/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs example-chat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls example-chat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/chat/npm-debug.log

**Comment by mikemintz** [comment]
Sometimes I get unusual errors when I upgrade node.js. Can you try `rm -rf node_modules` and try `npm install` and `npm start` again?

Here's the exact commands I run on my laptop without any problems:

```bash
$ node --version
v7.5.0
$ npm --version
4.1.2
$ git clone git@github.com:mikemintz/react-rethinkdb.git
$ cd react-rethinkdb/examples/chat
$ npm install
$ npm start
```

If I try to match your node version, it also works:

```bash
$ nvm install 6.10.0
$ nvm use 6.10.0
$ node --version
v6.10.0
$ npm --version
3.10.10
$ rm -rf node_modules/
$ npm install
$ npm start
```

Maybe there's something wrong with your paths? E.g. it looks a bit odd that you're running from `/home/chat` as opposed to a subdirectory, so maybe the chat example isn't properly checked out? Can you try copying my first group of commands exactly and see if that works?

**Comment by rafaelgilead** [comment]
Hello Friend,
The above error appeared because of the import function, after npm install worked. However, the following error appears now:

`Chat server started

/home/user/public_html/chat/node_modules/rethinkdb/ast.js:1462
          throw new err.ReqlDriverCompileError("Argument " + i + " to " + (this.st || this.mt) + " may not be `undefined`.");
          ^
ReqlDriverCompileError: Argument 1 to get may not be `undefined`.
    at ReqlDriverCompileError.ReqlError [as constructor] (/home/user/public_html/chat/node_modules/rethinkdb/errors.js:23:13)
    at ReqlDriverCompileError.ReqlCompileError [as constructor] (/home/user/public_html/chat/node_modules/rethinkdb/errors.js:35:51)
    at new ReqlDriverCompileError (/home/user/public_html/chat/node_modules/rethinkdb/errors.js:46:57)
    at Get.<anonymous> (/home/user/public_html/chat/node_modules/rethinkdb/ast.js:1462:17)
    at Get.RDBOp [as constructor] (/home/user/public_html/chat/node_modules/rethinkdb/ast.js:1466:8)
    at new Get (/home/user/public_html/chat/node_modules/rethinkdb/ast.js:1846:38)
    at /home/user/public_html/chat/node_modules/rethinkdb/ast.js:1068:43
    at Table.RDBVal.get (/home/user/public_html/chat/node_modules/rethinkdb/ast.js:1070:7)
    at AuthManager.tokenAuth (/home/user/public_html/chat/AuthManager.js:66:36)
    at sessionCreator (/home/user/public_html/chat/index.js:47:22)
    at Connection.start (/home/user/public_html/chat/node_modules/rethinkdb-websocket-server/dist/Connection.js:70:29)
    at WebSocketServer.<anonymous> (/home/user/public_html/chat/node_modules/rethinkdb-websocket-server/dist/index.js:131:16)
    at emitOne (events.js:96:13)
    at WebSocketServer.emit (events.js:188:7)
    at /home/user/public_html/chat/node_modules/ws/lib/WebSocketServer.js:88:14
    at completeHybiUpgrade2 (/home/user/public_html/chat/node_modules/ws/lib/WebSocketServer.js:274:5)

npm ERR! Linux 3.14.32-xxxx-grs-ipv6-64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! example-chat@0.0.0 start: `babel-node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the example-chat@0.0.0 start script 'babel-node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.`


already tried: npm install babel-cli -g
and nothing.

**Comment by rafaelgilead** [comment]
I use: npm install babel-preset-es2015 --save-dev

And nothing.

> babel-node index.js

/home/izzi/public_html/chat/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126
      if (!option) this.log.error("Unknown option: " + alias + "." + key, ReferenceError);
                           ^

TypeError: Cannot read property 'error' of undefined
    at OptionManager.mergeOptions (/home/izzi/public_html/chat/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:28)
    at OptionManager.addConfig (/home/izzi/public_html/chat/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/home/izzi/public_html/chat/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/home/izzi/public_html/chat/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at compile (/home/izzi/public_html/chat/node_modules/babel-core/lib/api/register/node.js:117:22)
    at normalLoader (/home/izzi/public_html/chat/node_modules/babel-core/lib/api/register/node.js:199:14)
    at Object.require.extensions.(anonymous function) [as .js] (/home/izzi/public_html/chat/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Linux 3.14.32-xxxx-grs-ipv6-64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! example-chat@0.0.0 start: `babel-node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the example-chat@0.0.0 start script 'babel-node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the example-chat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs example-chat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls example-chat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/izzi/public_html/chat/npm-debug.log

**Comment by mikemintz** [comment]
Have you made any changes to the chat example? If not, are the commands you're running any different from the example I gave?

```
$ git clone git@github.com:mikemintz/react-rethinkdb.git
$ cd react-rethinkdb/examples/chat
$ npm install
$ npm start
```

**Comment by rafaelgilead** [comment]
It worked now.
Another project installed in the root folder was interfering with the proper functioning.
